const path = require('path');
const dotenv = require('dotenv');
dotenv.config({ path: path.join(__dirname, '..', '.env') });

const mongoose = require('mongoose');
const Course = require('../src/models/Course');
const User = require('../src/models/User');
const Assignment = require('../src/models/Assignment');

const MONGO_URI = process.env.MONGO_URI;
if (!MONGO_URI) {
    console.error('MONGO_URI is not set in .env');
    process.exit(1);
}

// 5 highly-reliable, embed-friendly YouTube Video IDs from open educators (e.g. FreeCodeCamp, TraversyMedia)
const SAFE_VIDEO_IDS = [
    "bMknfKXIFA8", // React
    "W6NZfCO5SIk", // JavaScript
    "pkx2y8_I0sU", // Python
    "zJSY8tbf_ys", // Frontend
    "Oe421EPjeBE"  // Node.js
];

const COURSES = [
    { title: "HTML & CSS Full Course - Beginner to Pro", description: "Learn HTML5 and CSS3 from scratch.", category: "Web Development" },
    { title: "JavaScript Tutorial for Beginners", description: "Learn JavaScript in 1 hour.", category: "Web Development" },
    { title: "React JS Crash Course", description: "Get started with React in this crash course.", category: "Web Development" },
    { title: "Next.js 14 Full Course 2024", description: "Build and Deploy a Full Stack App.", category: "Web Development" },
    { title: "Node.js and Express.js - Full Course", description: "Learn Node.js and Express.", category: "Web Development" },
    { title: "Python for Beginners - Full Course", description: "Python syntax, data types, operators.", category: "Programming" },
    { title: "Java Tutorial for Beginners", description: "Learn Java programming from scratch.", category: "Programming" },
    { title: "C++ Programming Course for Beginners", description: "Learn C++ from basics to advanced.", category: "Programming" },
    { title: "C# Tutorial - Full Course for Beginners", description: "Learn C# programming.", category: "Programming" },
    { title: "Data Structures and Algorithms", description: "Comprehensive DSA course using Python.", category: "Programming" },
    { title: "UX/UI Design Course", description: "Master UX/UI Design principles.", category: "Design" },
    { title: "Figma UI Design Tutorial", description: "Learn Figma in an hour.", category: "Design" },
    { title: "Graphic Design Basics", description: "Learn typography, color theory.", category: "Design" },
    { title: "Digital Marketing Basics", description: "SEO, social media marketing.", category: "Marketing" },
    { title: "SEO Tutorial for Beginners", description: "Complete SEO basics.", category: "Marketing" },
    { title: "Business Analytics", description: "Understand data storytelling.", category: "Business" },
    { title: "Financial Accounting Basics", description: "Learn accounting equations.", category: "Business" },
    { title: "Machine Learning Full Course", description: "Learn Supervised Learning.", category: "Data" },
    { title: "Data Science Full Course", description: "Python, Pandas, NumPy.", category: "Data" },
    { title: "SQL Tutorial for Beginners", description: "Complete SQL database course.", category: "Math" },
    { title: "Statistics for Data Science", description: "Descriptive and inferential statistics.", category: "Math" },
    { title: "Linear Algebra full course", description: "Vectors, matrices, linear transformations.", category: "Math" },
    { title: "Cloud Computing Basics", description: "Introduction to AWS, Azure, GCP.", category: "Science" },
    { title: "Docker Tutorial for Beginners", description: "Learn containers, images.", category: "Web Development" },
    { title: "Kubernetes Crash Course", description: "Understanding K8s architecture.", category: "Web Development" }
];

async function run() {
    try {
        await mongoose.connect(MONGO_URI);
        
        const instructor = await User.findOne({ role: { $in: ['instructor', 'admin'] } }).select('_id');
        if (!instructor) {
            console.error('No instructor or admin user found! You must register an instructor first.');
            process.exit(1);
        }

        console.log("Found instructor/admin:", instructor._id);
        console.log("Cleaning up previously seeded courses/assignments...");
        
        await Course.deleteMany({ title: { $in: COURSES.map(c => c.title) } });
        // We will also delete related assignments generated by this script
        await Assignment.deleteMany({ title: { $regex: /^Assignment:/ } });

        console.log("Seeding 25 courses with safe YouTube videos and Assignments...");

        let createdCount = 0;

        for (let i = 0; i < COURSES.length; i++) {
            const c = COURSES[i];
            const safeYtId = SAFE_VIDEO_IDS[i % SAFE_VIDEO_IDS.length];

            const courseData = {
                title: c.title,
                description: c.description,
                category: c.category,
                instructor: instructor._id,
                coverImage: `https://img.youtube.com/vi/${safeYtId}/maxresdefault.jpg`,
                status: 'approved',
                enrolledStudents: [],
                videos: [
                    {
                        title: `${c.title} - Video Lecture`,
                        videoUrl: `https://www.youtube.com/watch?v=${safeYtId}`
                    }
                ],
                objectives: ["Understand the fundamentals", "Build hands-on projects", "Master the concepts"],
                outcomes: ["Ready for real-world application", "Solid foundation for advanced topics"],
                syllabus: [
                    {
                        moduleTitle: "Module 1: Video Lecture",
                        lessons: ["Watch the integrated session", "Complete the follow-up assignment"]
                    }
                ]
            };
            
            const savedCourse = await Course.create(courseData);
            
            const assignmentData = {
                title: `Assignment: ${c.title}`,
                description: `Please complete the follow-up exercises for the video session: "${c.title}". Ensure you have watched the entire embedded video lecture before proceeding.`,
                type: 'programming',
                course: savedCourse._id,
                instructor: instructor._id,
                dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000), // 7 days from now
                totalMarks: 100
            };
            await Assignment.create(assignmentData);

            createdCount++;
        }

        console.log(`Successfully created ${createdCount} awesome YouTube-integrated courses and their corresponding Assignments!`);

    } catch (err) {
        console.error("Error seeding courses:", err);
    } finally {
        await mongoose.disconnect();
    }
}

run();
